### ISSUE TITLE
Read AcoustID from tags

### ISSUE THREAD

**Issue by diogocp** [andrewrk/libgroove#104]
I use [Picard](https://picard.musicbrainz.org/) to tag my music, so many of the files have an AcoustID tag (e.g. `ACOUSTID_ID=311cb6a3-f39d-4c29-9927-4e376a374aa0`). I don't think there is any use for the fingerprint other than looking up the ID, so there is no need to spend CPU time calculating it.

See also #103.

**Comment by andrewrk** [comment]
libgroove exposes all the metadata it finds. Is libgroove failing to expose the `ACOUSTID_ID` tag? or is this perhaps a Groove Basin issue?

**Comment by diogocp** [comment]
Yes, I think it is better to handle this in Groove Basin, like #103.
