### ISSUE TITLE
On Cent OS 7, make fails with errors related to inttypes.h

### ISSUE THREAD

**Issue by tanhaa** [andrewrk/libgroove#119]
Several errors such as this one take place on CentOS 7 when running make:

```/home/centos/libgroove/src/playlist.cpp: In function ‘int init_filter_graph(GroovePlaylist*, GrooveFile*)’:
/home/centos/libgroove/src/playlist.cpp:351:79: error: expected ‘)’ before ‘PRIx64’
             "time_base=%d/%d:sample_rate=%d:sample_fmt=%s:channel_layout=0x%" PRIx64,```

Required editing playlist.cpp to add 
```
#define __STDC_FORMAT_MACROS
#include <inttypes.h>
```

Alternatively, adding only
```
#include <cinttypes> 
```
worked as well on the system

Please fix

**Comment by andrewrk** [comment]
Does it work with only this (sans the `#define __STDC_FORMAT_MACROS`)?

```c
#include <inttypes.h>
```

**Comment by andrewrk** [comment]
Nevermind. I saw the IRC chat log.

**Comment by andrewrk** [comment]
By the way, don't use git master right now; use the latest release. I have some bugs to work out with master branch before releasing 5.0.0.

**Comment by tanhaa** [comment]
ah.. looks like I installed from master.  If there are any bugs with my installation, I'll install from the latest release.  Thanks for being on top of this!
