### ISSUE TITLE
`av_free_packet` deprecated

### ISSUE THREAD

**Issue by astronouth7303** [andrewrk/libgroove#125]
Building libgroove through AUR:

```
/tmp/yaourt-tmp-astronouth7303/aur-libgroove/src/libgroove-4.3.0/groove/playlist.c: In function ‘decode_one_frame’:
/tmp/yaourt-tmp-astronouth7303/aur-libgroove/src/libgroove-4.3.0/groove/playlist.c:598:9: error: ‘av_free_packet’ is deprecated [-Werror=deprecated-declarations]
         av_free_packet(pkt);
         ^
In file included from /usr/include/libavformat/avformat.h:318:0,
                 from /tmp/yaourt-tmp-astronouth7303/aur-libgroove/src/libgroove-4.3.0/groove/file.h:13,
                 from /tmp/yaourt-tmp-astronouth7303/aur-libgroove/src/libgroove-4.3.0/groove/playlist.c:8:
/usr/include/libavcodec/avcodec.h:4040:6: note: declared here
 void av_free_packet(AVPacket *pkt);
      ^
/tmp/yaourt-tmp-astronouth7303/aur-libgroove/src/libgroove-4.3.0/groove/playlist.c:602:5: error: ‘av_free_packet’ is deprecated [-Werror=deprecated-declarations]
     av_free_packet(pkt);
     ^
In file included from /usr/include/libavformat/avformat.h:318:0,
                 from /tmp/yaourt-tmp-astronouth7303/aur-libgroove/src/libgroove-4.3.0/groove/file.h:13,
                 from /tmp/yaourt-tmp-astronouth7303/aur-libgroove/src/libgroove-4.3.0/groove/playlist.c:8:
/usr/include/libavcodec/avcodec.h:4040:6: note: declared here
 void av_free_packet(AVPacket *pkt);
      ^
cc1: all warnings being treated as errors
CMakeFiles/groove.dir/build.make:86: recipe for target 'CMakeFiles/groove.dir/groove/playlist.c.o' failed
make[2]: *** [CMakeFiles/groove.dir/groove/playlist.c.o] Error 1
CMakeFiles/Makefile2:365: recipe for target 'CMakeFiles/groove.dir/all' failed
make[1]: *** [CMakeFiles/groove.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Ichimonji10** [comment]
If any candidate patches are created, I'll be happy to test them out.

**Comment by craftyguy** [comment]
This was actually fixed already in this commit: https://github.com/andrewrk/libgroove/commit/aed5104a92089e9b56ac5a47935980f9f07f72b5

Not sure why the developer is keeping this ticket open though.

**Comment by Ichimonji10** [comment]
> This was actually fixed already in [...]

Great! Glad to see it.

...I should have made that connection earlier, before posting here. What a brain fart.

> @Ichimonji10 I was the one that reported the build error for libgroove-git to you in AUR and this was why I flagged the package out of date since it was not pulling in this commit :)

Yup, I remember seeing that message. I'm unsure what's causing that build failure, but I'd be surprised if the current libgroove git repository was not being cloned. Such a failure would indicate an issue with makepkg or one of its dependencies.

Try uninstalling sdl2 and building the current libgroove-git package. You can get back to me here on via email (check your inbox). (sdl2 has been dropped for the current libgroove version, and uninstalling it silenced a warning for me.)

**Comment by andrewrk** [comment]
Oops, forgot to close this after fixing it.

I really need to get 5.0.0 out! Let me see if I can do that today.
