### ISSUE TITLE
libgroove cannot be compiled with Visual C++

### ISSUE THREAD

**Issue by CyberSinh** [andrewrk/libgroove#128]
I try to compile libgroove with Visual C++ 2015 but it can't compile the code because pthread.h (Unix specific library) and stdatomic.h (VC 2015 seems to support atomic only for C++ , but without C specific header) files are missing.

Do you plan to change libgroove to be compilable with VC 2015 (as libsoundio is) in the 5.0 milestone?

Thanks.

**Comment by CyberSinh** [comment]
Andrew, can you ear me?

**Comment by andrewrk** [comment]
Hello, yes it is planned to be able to build libgroove with VC 2015 in the 5.0.0 milestone. Progress has been slow though...

**Comment by CyberSinh** [comment]
Hello. Great news!
When do you think to be able to release the v5?
Thanks you very much.

**Comment by CyberSinh** [comment]
Hi,

There is no major commit in libgroove since november 2015. 
Do you still work on this project?

Thanks.
