### ISSUE TITLE
avcodec_decode_audio4() is deprecated in FFmpeg 3.1

### ISSUE THREAD

**Issue by CyberSinh** [andrewrk/libgroove#130]
libgroove uses FFmpeg deprecated API: 
'avcodec_decode_audio4': was declared deprecated in playlist.c

More info at:
https://ffmpeg.org/doxygen/3.1/group__lavc__encdec.html

Regards

**Comment by JoeyHoutenbos** [comment]
Would be really nice to have FFmpeg 3.4 support. @andrewrk do you plan on doing this?

**Comment by krytarowski** [comment]
Still valid. Tested on NetBSD/amd64 with pkgsrc.
