### ISSUE TITLE
Ubuntu 15.04 PPA Support

### ISSUE THREAD

**Issue by CalebMorris** [andrewrk/libgroove#87]
Are there plans to add apt support of libgroove to 15.04?

**Comment by andrewrk** [comment]
libgroove ships with ubuntu 15.04 already.

**Comment by andrewrk** [comment]
http://packages.ubuntu.com/source/vivid/libgroove

**Comment by CalebMorris** [comment]
Awesome.
Was following README instructions for ubu and the PPA doesn't work for vivid.
This is good to know.
