### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by diogocp** [andrewrk/libgroove#99]
I created an ebuild for libgroove. See gentoo/gentoo#22.

**Comment by andrewrk** [comment]
Nice, if that gets merged I'll update the README. Anything else I can do?

**Comment by andrewrk** [comment]
hey it looks like that is a mirror. I'm guessing you need to send patches to a mailing list for gentoo.

**Comment by diogocp** [comment]
Nope, just an FYI ;)

I also opened [a bug](https://bugs.gentoo.org/show_bug.cgi?id=558190), but I think they're accepting PRs now. Gentoo just moved to Git last week, so I haven't figured it out yet.

**Comment by andrewrk** [comment]
Cool. Remind me to update the README when this gets merged :)
